version: "3"
services:

  mariadb:
    container_name: domjudge-mariadb
    image: mariadb:latest
    command: --max_connections=1000 --innodb-log-file-size=536870912
    env_file: domserver.env
    restart: always

  domserver:
    container_name: domjudge-domserver
    image: domjudge/domserver:latest
    env_file: domserver.env
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mariadb
